require 'rubygems'
require 'test/unit'
require 'ruby-debug'
require 'nokogiri'
require 'mocha'

require 'reform/base'
require 'reform/select_options'
require 'reform/field/base'
require 'reform/field/text'
require 'reform/field/select'
require 'reform/field/text_area'
require 'reform/field/hidden'

require 'spec/fixture'
require 'spec/declare'
require 'spec/render'
require 'spec/select_options'
require 'spec/field/text'
require 'spec/field/select'
require 'spec/field/hidden'
