require 'rubygems'
require 'test/unit'
require 'ruby-debug'
require 'nokogiri'
require 'mocha'

require 'reform/base'
require 'reform/select_options'
require 'reform/field/base'
require 'reform/field/text'
require 'reform/field/select'
require 'reform/field/text_area'
require 'reform/field/hidden'

require 'test/fixture'
require 'test/declare'
require 'test/render'
require 'test/value'
require 'test/select_options'
require 'test/field/text'
require 'test/field/select'
require 'test/field/hidden'
